name: 'Detect Reusable Workflow Repository and Ref'
description: 'Get the current reusable workflow repository name and ref. Requires "id-token: write" permission'
outputs:
  repository:
    description: The current workflow repository, format org/repository
  ref:
    description: The current workflow reference
runs:
  using: 'composite'
  steps:
    - run: | 
        status_code=$(curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=slsa-framework/slsa-github-generator-go/builder" -o jwt.json -w '%{http_code}')
        if [[ $status_code -ge 400 ]]; then
            error_msg=$(jq -r .message jwt.json 2>/dev/null || echo 'unknown error')
            echo "Failed to get OIDC token from GitHub, response $status_code: $error_msg"
            exit 1;
        fi
        export WORKFLOW_REF=$(cat jwt.json | jq -r '.value' | cut -d "." -f2 | base64 -d | jq -r '.job_workflow_ref')
        if [ -z $WORKFLOW_REF ]; then
          echo "OIDC token parsing failure: job_workflow_ref could not be retrieved"
          exit 1;
        fi
        echo "::set-output name=repository::$(echo $WORKFLOW_REF | cut -d "@" -f1 | cut -d '/' -f1-2)"
        echo "::set-output name=ref::$(echo $WORKFLOW_REF | cut -d "@" -f2)"
      shell: bash