name: PR units
on: [pull_request, workflow_dispatch]

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4

      - name: setup-go
        uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v3.2.0
        with:
          go-version: "1.18"

      - name: detect-workflow tests
        run: |
          set -euo pipefail

          cd .github/actions/detect-workflow

          # Download dependencies.
          go mod vendor

          # Test.
          go test -mod=vendor -v ./...

      - name: API tests
        run: |
          # Tests unit tests, including in generic and go builders
          set -euo pipefail

          # Download dependencies.
          go mod vendor

          # Test.
          go test -mod=vendor -v ./...

      - name: Builder builds
        run: |
          set -euo pipefail

          # Go tests.
          cd internal/builders/go/

          # Download dependencies.
          go mod vendor

          # Build Go builder.
          go build -mod=vendor

          # Generic tests.
          cd ../generic

          # Download dependencies.
          go mod vendor

          # Build Generic builder.
          go build -mod=vendor

  check-verifier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
        with:
          path: generator

      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
        with:
          path: verifier
          repository: slsa-framework/slsa-verifier

      - name: Check verifier references
        run: |
          # The first sha in SHA256SUM.md is the latest verifier release sha
          expected_sha=$(cat verifier/SHA256SUM.md | grep -e -m 1  -w -o '[0-9a-f]\{64\}')

          # The first vX.Y.Z in SHA256SUM.md is the latest verifier release version
          expected_version=$(cat verifier/SHA256SUM.md | grep -e 'v[0-9].[0-9].[0-9]' -o -m 1 -w | head -1)

          # Check for expected verifier releases in the builders
          cd generator
          grep -r -e 'VERIFIER_RELEASE_BINARY_SHA256: [0-9a-f]\{64\}' --include=*.yml |
          while read -r  line ; do
            sha=$(echo $line | grep -o '[0-9a-f]\{64\}')
            file=$(echo $line | awk '{print $1;}')
            if [ "$sha" != "$expected_sha" ]; then
              echo "SHA out of date in file $file expected $expected_sha"
              error=1
            fi
          done

          grep -r -e 'VERIFIER_RELEASE: v[0-9].[0-9].[0-9]' --include=*.yml |
          while read -r  line ; do
            version=$(echo $line | grep -o 'v[0-9].[0-9].[0-9]')
            file=$(echo $line | awk '{print $1;}')
            if [ "$version" != "$expected_version" ]; then
              echo "Verifier version out of date in file $file expected $expected_version"
              error=1
            fi
          done

          if [ -n "$error" ]; then
            exit 1
          fi