name: pre-submit env var

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: read-all

jobs:
  debug:
  runs-on: ubuntu-latest
  steps:
    - run: |
      echo "Github repository: ${GITHUB_REPOSITORY}"
      echo "Github workflow: ${GITHUB_WORKFLOW}"
      echo "Github workflow sha: ${GITHUB_WORKFLOW_SHA}"
      echo "Github workflow ref: ${GITHUB_WORKFLOW_REF}"
